user:
    pattern:  /
    defaults: { _controller: "ZeteqUserBundle:User:index" }

user_show:
    pattern:  /{id}/show
    defaults: { _controller: "ZeteqUserBundle:User:show" }

user_new:
    pattern:  /new
    defaults: { _controller: "ZeteqUserBundle:User:new" }

user_create:
    pattern:  /create
    defaults: { _controller: "ZeteqUserBundle:User:create" }
    requirements: { _method: post }

user_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "ZeteqUserBundle:User:edit" }

user_change_password:
    pattern:  /{id}/change_password
    defaults: { _controller: "ZeteqUserBundle:User:change_password" }
user_update_password:
    pattern:  /{id}/update_password
    defaults: { _controller: "ZeteqUserBundle:User:update_password" }
    requirements: { _method: post|put }


user_update:
    pattern:  /{id}/update
    defaults: { _controller: "ZeteqUserBundle:User:update" }
    requirements: { _method: post|put }

user_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "ZeteqUserBundle:User:delete" }

