parameters:
#    zeteq_admin.example.class: Zeteq\AdminBundle\Example

services:
#    zeteq_admin.example:
#        class: %zeteq_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
