fm_elfinder:
    locale: %locale%
    editor: ckeditor # other choices are tinymce or simple
    showhidden: false
    connector:
        debug: true # defaults to false
        roots:       # at least one root must be defined
            uploads:
                driver: LocalFileSystem
                path: upload/images
                upload_allow: ['image/png', 'image/jpg', 'image/jpeg']
                upload_deny: ['all']
                upload_max_size: 20M
